version: '3'
services:
  ece566:
    cap_add:
      - SYS_PTRACE
    security_opt: # options needed for debugging
      - seccomp:unconfined
      - apparmor:unconfined
    privileged: true
    build: .
    volumes:
      - .:/ece566
    container_name: ece566
    ports:
       - "2222:22"