name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose up -d
    - name: Traverse and build tutorial starters with make
      run: docker-compose exec -T ece566 /bin/bash -c 'for d in tutorials/* ; do echo $d && make -C $d && make clean -C $d; done'
    - name: Traverse and build tutorial starters with CMake
      run: docker-compose exec -T ece566 /bin/bash -c 'for d in tutorials/* ; do echo $d && cd $d && mkdir build && cd build && cmake .. && make && cd .. && rm -rf build && cd ../..; done'