name: Docker Image CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose build
    - name: Traverse and build tutorial starters with make
      run: for d in tutorials/* ; do echo $d && make -C $d && make clean -C $d; done
    - name: Traverse and build tutorial starters with CMake
      run: for d in tutorials/* ; do echo $d && cd $d && mkdir build && cd build && cmake .. && make && cd .. && rm -rf build && cd ../..; done